# Build settings
title: "R&D Documentation"
### Built settings ###

url: "https://vanamsandeep-test.github.io"
baseurl: "/testrepo"

github_username: vanamsandeep
remote_theme: pages-themes/leap-day@v0.2.0

markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
source: 'docs'
html-proofer:
  checks:['Links']
plugins:
  - jekyll-timeago
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-default-layout
  - jemoji
    
